### ISSUE TITLE
Sidekiq support would be great!

### ISSUE THREAD

**Issue by fredngo** [dtmtec/dyno_scaler#1]
More of a feature request than an issue. :)

**Comment by vicentemundim** [comment]
Definitively!

I think that the path would be to create a client-side and a server-side [middleware](https://github.com/mperham/sidekiq/wiki/Middleware) that would act like after_enqueue and after_perform hooks on Resque.

The thing is that I have no experience with sidekiq, so you're welcome to send a pull request!

**Comment by fredngo** [comment]
If I could ever find some time to help out with this, I might jump in. I'll let you know!

**Comment by fredngo** [comment]
Awesome!
